=== shivkumar98/XMLExamples/11 Numbers XML/NumbersSchema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
	targetNamespace="http://www.example.org/NumbersSchema"
	xmlns:tns="http://www.example.org/NumbersSchema"
	elementFormDefault="qualified">
	
	<element name="numbers" type="tns:numbersType" />

	<complexType name="numbersType" mixed="true">
		<sequence>
			<element name="description" type="string" />
			<element name="number" maxOccurs="unbounded">
				<complexType>
					<sequence>
						<element name="factor" minOccurs="0" maxOccurs="unbounded">
							<complexType>
								<attribute name="value" type="int" />
							</complexType>
						</element>
					</sequence>
					<attribute name="value" type="int" />
					<attribute name="square" type="int" />

				</complexType>
			</element>
		</sequence>
	</complexType>
</schema>

=== shivkumar98/XMLExamples/11 Numbers XML/Script Output.xml
<?xml version="1.0" encoding="UTF-8"?>
<numbers xmlns="http://www.example.org/NumbersSchema"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.example.org/NumbersSchema NumbersSchema.xsd ">
	1 For more information about XML processing in Groovy see chapter 14. 2
	For any given x the factors are all numbers y such that x % y == 0.
	Listing 11.1 XML example data: Squares and factors of 10â€“15
	www.it-ebooks.info
	346 CHAPTER 11 Working with builders
	<description>Squares and factors of 10..15</description>
	<number value='10' square='100'>
		<factor value='2' />
		<factor value='5' />
	</number>
	<number value='11' square='121' />
	<number value='12' square='144'>
		<factor value='2' />
		<factor value='3' />
		<factor value='4' />
		<factor value='6' />
	</number>
	<number value='15' square='196'>
		<factor value='2' />
		<factor value='7' />
	</number>
	<number value='15' square='225'>
		<factor value='3' />
		<factor value='5' />
	</number>
</numbers>
